modules_by_course   =   '../data/cursos_modulo.csv'
last_interaction    =   '../data/ultima_interaccion_usuarios_modulo.csv'
total_interaction   =   '../data/total_interacciones_usuario_modulo.csv'
date_courses        =   '../data/date.csv'
enrollment_data     =   '../data/enrollment_train.csv'
data_interactions   =   '../data/log_train.csv'